-- Run this entire file in Supabase SQL Editor.
-- The application uses a server-only Supabase secret key, so these tables
-- are intentionally not exposed to browser clients.

create extension if not exists pgcrypto;

create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  title text not null default 'New chat',
  created_at timestamptz not null default now()
);

create index if not exists conversations_user_id_created_at_idx
  on public.conversations(user_id, created_at desc);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  user_id uuid not null,
  role text not null check (role in ('user','assistant','system')),
  content text not null,
  created_at timestamptz not null default now()
);

create index if not exists messages_conversation_id_created_at_idx
  on public.messages(conversation_id, created_at);

create index if not exists messages_user_id_idx
  on public.messages(user_id);

create table if not exists public.memories (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  memory text not null,
  importance integer not null default 5 check (importance between 1 and 10),
  created_at timestamptz not null default now()
);

create index if not exists memories_user_id_importance_idx
  on public.memories(user_id, importance desc, created_at desc);

-- This project deliberately keeps the tables server-only.
-- Do not put the Supabase secret key in frontend code.
alter table public.conversations enable row level security;
alter table public.messages enable row level security;
alter table public.memories enable row level security;

-- No public/authenticated policies are created.
-- The Cloudflare Function uses the server-side secret key.
